# Override to use MySQL as a backing store for datahub-gms.
---
version: '3.8'
services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:5.7
    env_file: env/docker.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqldata:/var/lib/mysql

  datahub-gms:
    env_file: ../datahub-gms/env/docker.env
    depends_on:
      - mysql

volumes:
  mysqldata:
